### ISSUE TITLE
relative config paths

### ISSUE THREAD

**Issue by slipperysaxophone** [pubgeo/core3d-metrics#12]
The paths for files specified in a config are not treated as relative to the config, but instead relative to the run_geometrics.py 

So given the following filesystem layout:
* geometrics
  * run_geometrics.py
* binaries/
  * configs/
    * a.config (references ../data/some_data)
  * data/
    * some_data

Running 'python3 run_geometrics.py -c ../binaries/configs/a.config' from the geometrics folder will try to use geometrics/data/some_data instead of binaries/data/some_data

It would make the most sense for relative paths in a config be relative to the config instead of the program running it.

**Comment by drewgilliam** [comment]
Fixed by #13 - @pubgeo please close.
