### ISSUE TITLE
Schema Validation Error

### ISSUE THREAD

**Issue by cstutts** [pubgeo/core3d-metrics#21]
config.py appears to be checking the input configuration file against a JSON schema. We're using the test harness config text files provided on 12/18. This causes raise jsonschema.exceptions.ValidationError('validation error') on line 126 of config.py to occur.

Should this validation be skipped if the input file is text format?

Craig

**Comment by slipperysaxophone** [comment]
I believe your config is failing because it includes the outdated field 'ModelFileName' which was set to 0 during the 12/18 release. Why this is causing a JSON validation error is something I will look into.

Try using a newer config, or request one from @pubgeo

**Comment by drewgilliam** [comment]
@slipperysaxophone is correct - configuration validation does not permit extraneous properties ("additionalProperties" is set to false for most configuration sections).   Validation is fully compatible with aoi-examples such as [aoi-example.config](https://github.com/pubgeo/core3d-metrics/blob/master/aoi-example/aoi-example.config)

Validation additionally prints details immediately prior to the ValidationError indicating how a configuration file failed validation.  Please refer to this print out for more information.

@slipperysaxophone @pubgeo - I recommend closing this issue.

**Comment by cstutts** [comment]
That fixed it. I created a pull request to fix a JSON decode issue. The examples run after that change.
