### ISSUE TITLE
Add a tag to help with conda package versions

### ISSUE THREAD

**Issue by danlipsa** [pubgeo/core3d-metrics#43]
I am a member of core3d involved in building conda packages for code used in core3d including cored-metrics.
For this, it would be useful to tag the git source code. This will help us to automatically set the package version, order packages and see the correspondence between the package and code.
We'll need 'annotated tags' set like this:
git tag -a v0.1 -m "my version 0.1"

Thanks!

**Comment by pubgeo** [comment]
Tags are now included

**Comment by danlipsa** [comment]
Great, thanks!
